### ISSUE TITLE
StackPrice doesn't work anymore

### ISSUE THREAD

**Issue by Xericore** [Dandielo/dtlTraders#51]
Using latest dtlTraders-3.3-SNAPSHOT.jar (Build 25) as well as spigot-1.8.3 and citizens-2.0.15 (Build 1220).

Hello, the StackPrice feature doesn't seem to work anymore. Here's the part of the NPC's saves.yml:
```
      trader:
        type: server
        owner-uuid: none
        patterns: []
        sell:
        - bow d:0 s:6 a:1 p:16.99
        - arrow s:0 a:64 p:124.99 .sp
        buy: []
```

I am assuming that ".sp" is the persisted StackPrice-flag and I also know that the trader had the correct price earlier. In this example, the arrows always cost a*p (e.g. 64*124.99). 
When I try to change the StackPrice by clicking the item in manager mode, the console says "Changed stack price: true/false", but that doesn't affect the price, it always stays a*p.
